### ISSUE TITLE
Actual results of compensation not as good as results observed during validation phase

### ISSUE THREAD

**Issue by sapoluri** [BingyaoHuang/CompenNet#4]
I ran your code with my setup and attached is the result for one of the test images.

I see that the images expected, post compensation look very good and the color patches I added almost completely disappear. However, when I project the compensation images from the prj folder and capture the images, the results don't look anywhere close to the expectation.

I don't think it's because of the solid color patches being too saturated because in your testing, you used screens that were just as saturated.

I am using a pretty old projector (Powerlite 7900P) projecting at 800x600 and an Intel realsense RGB camera capturing at 1920x1080. Fixed exposure, fixed Whitebalance.
I trained with 100 images, l1+ssim, 1000 iterations

[img_gray_color](https://user-images.githubusercontent.com/43018757/86818858-c0e41d00-c03b-11ea-8804-0d8021a9ad94.png) - solid gray projected on my screen
[img_0006](https://user-images.githubusercontent.com/43018757/86818857-c04b8680-c03b-11ea-951f-0a5c37fb4d80.png) - original image
[img_0006_Color](https://user-images.githubusercontent.com/43018757/86818853-bf1a5980-c03b-11ea-83bc-7fc492f722f1.png) - capture of the original image projected on screen
[img_0006_Color_corrected ](https://user-images.githubusercontent.com/43018757/86818863-c2154a00-c03b-11ea-9901-ca27342b10fb.png)- capture of the compensation image on screen
[img_0006_generated](https://user-images.githubusercontent.com/43018757/86818862-c2154a00-c03b-11ea-9a40-88f0d89fd766.png) - generated by the model as the expected output post compensation

How did the results of projecting the compensated image look like in your lab? Were they as good as the generated output expected it to be?
Would using a more modern projector give better results when projecting a compensated image? (I assume it should. Given that the contrast ratio would be vastly better)

**Comment by BingyaoHuang** [comment]
The setup-independent surrogate benchmark can be viewed as an upper bound of the model. But the real compensation quality is also restricted by the physical limitations of the hardware, e.g., the dynamic range of the camera and the projector and the lens/sensor quality.

In the beginning, we tried cheap hardware but got very poor results. As mentioned in the paper, our current setup consists of 
1.	A Canon 6D DSLR camera, because it has a much better image quality than webcams or an Intel realsense RGB camera.
2.	A ViewSonic PJD7828HDL DLP projector with a high dynamic range, brightness and contrast.

For more details, please refer to [supplementary](https://www3.cs.stonybrook.edu/~hling/publication/CompenNet_sup.pdf) Sec. 3.
