### ISSUE TITLE
Process used to get png images using Canon 6D

### ISSUE THREAD

**Issue by sapoluri** [BingyaoHuang/CompenNet#5]
did you capture RAW images and then use a photoediting software to generate gamma corrected png images?

**Comment by BingyaoHuang** [comment]
We captured the CompenNet dataset using live view with tethered shooting and the output images are png. Although capturing RAW then converting to png may produce a better image quality, it was time consuming. In fact, even live view with tethered shooting was slow since Canon 6D only supports USB 2.0 (see [supplementary](https://www3.cs.stonybrook.edu/~hling/publication/CompenNet_sup.pdf) Sec. 3.). Thus, in [CompenNet++](https://github.com/BingyaoHuang/CompenNet-plusplus) we used an Elgato Cam Link 4K video capture card (connected to the Canon 6D hdmi mini port) to speed up the data capturing process.

**Comment by sapoluri** [comment]
I installed Canon EOS Utility to capture images from my laptop. However, the options for capture are RAW and JPEG only.

Did you use "Digital Photo Professional" in conjunction with it?

**Comment by sapoluri** [comment]
What software did you use to do tethered shooting?

**Comment by BingyaoHuang** [comment]
http://digicamcontrol.com/
